name: DungeonsXXL
main: me.kylofz.miraya.dungeon.xxl.DungeonsXXL
version: ${project.version}${buildNo}
author: Daniel Saukel
description: ${project.description}
website: ${project.url}
depend: [DungeonsXL]
