name: MirayaDungeon
main: me.kylofz.miraya.dungeon.DungeonsXL
version: ${project.parent.version}${buildNo}
authors: [kylofz, Frank Baumann, Milan Albrecht, Tobias Schmitz, Daniel Saukel]
description: ${project.parent.description}
website: ${project.parent.url}
depend: [MirayaAPI-Runtime]
softdepend: [CommandsXL, Vault, Citizens, CustomMobs, InsaneMobs, MythicMobs, HolographicDisplays, LWC, PlaceholderAPI, Parties]
commands:
  mirayadungeon:
    description: Reference command for MirayaDungeon.
    aliases: [dxl,dungeon,dungeonsxl]
api-version: '26.2'
